---
name: Releases

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'audio_data_gui.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: edit_mp4
          options: --onefile, --name "edit_mp4", --windowed, --icon favicon_light.ico, --add-data "favicon_light.ico;./", --collect-data customtkinter

  release-build:
    needs: pyinstaller-build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: edit_mp4
      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload artifact
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          generateReleaseNotes: true
          artifacts: edit_mp4.exe
