---
name: Releases

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    # Timeout of 15 mins
    timeout-minutes: 15
    strategy:
      matrix:
        # https://devguide.python.org/versions
        python-version: [ '3.11' ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}
#          # Options are pip, pipenv, or poetry
#          cache: "pip"
#          cache-dependency-path: '**/requirements.txt'
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#           if (Test-Path requirements.txt) { pip install -r requirements.txt }
#        shell: pwsh

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: ${{ matrix.python-version }}
          spec: 'audio_data_gui.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: edit_mp4
          options: >
            --onefile,
            --name "edit_mp4",
            --windowed,
            --icon logo_light.png,
            --add-data "logo_light.png:.",
            --collect-data customtkinter,
            --collect-data mutagen

  release-build:
    needs: pyinstaller-build
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: edit_mp4

      - name: Zip artifact for deployment
        run: |
          zip edit_mp4-linux.zip edit_mp4
          zip edit_mp4-windows.zip edit_mp4.exe
          zip edit_mp4-macos.zip edit_mp4.app/ -r

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload artifact
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          generateReleaseNotes: true
          artifacts: "*.zip"
