---
name: Releases

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    # Timeout of 15 mins
    timeout-minutes: 15
    strategy:
      matrix:
        # https://devguide.python.org/versions
        python-version: [ '3.11' ]
        os: [ windows-latest ]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: ${{ matrix.python-version }}
          spec: 'audio_data_gui.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: Manipulator-${{ matrix.os }}
          options: >
            --onefile,
            --name "Manipulator-${{ matrix.os }}",
            --windowed,
            --icon favicon_light.ico,
            --add-data "favicon_light.ico:./",
            --collect-data customtkinter,
            --collect-data mutagen
            --hidden-import PIL._tkinter_finder

  release-build:
    needs: pyinstaller-build
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: Manipulator
          pattern: Manipulator-*
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R

      - name: Zip artifact for deployment
        run: |
          zip -r Manipulator-windows.zip Manipulator/Manipulator-windows-latest.exe
        # zip -r Manipulator-linux.zip Manipulator-ubuntu-latest/
        # zip -r Manipulator-macos.zip Manipulator-macos-latest/

      - name: Upload artifact
        uses: ncipollo/release-action@v1
        with:
          prerelease: false
          generateReleaseNotes: true
          artifacts: "*.zip"
